Image Processing Assignment


'''In this project, you will have to create an image-filtering tool that follows the same concept as the Focal Statistics from ArcGIS1. The idea is to create a moving window that calculates different statistics for every pixel neighborhood, given a specific size window. For example, let us take an image with gray values and a filtering window of 3 by 3 pixels to calculate a maximum filter (Figure 1). The center of the filtering window will be the object of focus every calculation step. Then, the pixel with higher value within the filtering window is assigned to the central pixel. This procedure runs through the whole image, resulting in a maximum filtered image. The same concept would be used for minimum, mean, standard deviation and variance descriptors.

You are allowed to create as many functions as you want. The design of the script is entirely up to you.
Good luck!
''''



<img src="images/Pic1.jpg" style="width: 650px"/>

Figure 1, the filtering window is a square (window length = window width). However, you can 
have circular windows (Figure 2a), rectangular windows (Figure 2b) or wedge windows (Figure 2c). 
The important issue to be aware of when window shapes are concerned, is that the central pixel 
must be in the right position, as highlighted in red in Figure 2.   

<img src="images/Pic2.jpg" style="width: 650px"/>

1. Implement a function that creates a filtering window based on the user input. These inputs must be basic parameters (i.e. radius, size and/or angles) of the filtering window, including shape type.

In [3]:
import numpy as np


'''
So far, I build up two functions: One general function (focsta) which 
should be able to do all shapes in the end of our project.
The second function is squarefun, which can calculate the max for a square shape.
The way I did it, other functions (mean etc) should be implemented very easy.
For the other shapes, I suggest building up other functions like I did for the first.

Please search for bugs and try around with my code. I hope and think we can use it.
Manu, please dont be too hard on me :)
'''



# functions for each shape!

def squarefun(data, diameter):
    data = np.array(data) #
              
    # diameter must be odd, test for it
    if diameter%2==0:
        raise ValueError('Diameter must be a odd integer')
    
    # filling newdata array with zeros
    newdata = np.zeros(data.shape)
    
    # window size
    wsize = int((diameter-1)/2)
    
    
    
    for col in range(np.size(data, 1)): # rows
        for row in range(np.size(data, 0)):  # columns
            
            

            ### border cases ###
            
            # all corners:
            if col < wsize and row < wsize: # topleft
                window = data[:row+wsize+1, :col+wsize+1]
                #print('bot in topleft case \n', bot)
                
            elif col < wsize and row >= np.size(data, 0)-wsize: # botleft
                window = data[row-wsize:, :col+wsize+1]
                #print('top in botleft case \n', top)

                
            elif col >= np.size(data, 1)-wsize and row < wsize: # topright
                window = data[:row+wsize+1, col-wsize:]
                #print('bot in the topright case \n', bot)
                
            elif col >= np.size(data, 1)-wsize and row >= np.size(data, 0)-wsize: # botright
                window = data[row-wsize:, col-wsize:]
                #print('top in the botright case \n', top)

                
            # all borders:
            elif col < wsize: # left border
                window = data[row-wsize:row+wsize+1, :col+(wsize)+1]
                #print('left border case: \n', middle)
                
            elif row >= np.size(data, 0)-wsize: # bot border
                window = data[row-wsize:, col-wsize:col+wsize+1]
                #print('bot border case \n', middle)
                
            elif col >= np.size(data, 1)-wsize: # right border
                window = data[row-wsize:row+wsize+1, col-wsize:]
                #print('right border case \n', middle)
                
            elif row < wsize: # top border
                 window = data[:row+wsize+1, col-wsize:col+wsize+1]
                #print('top border case \n', middle)
            
            
            
            else: # normal case
                window = data[row-wsize:row+wsize+1, col-wsize:col+wsize+1]
                #print('normal case \n', middle)
            

            # finding the maximum
            newdata[row, col] = np.max(window)
            #print(newdata)     


    return newdata
    
    
    
    
    

# Endfunction - so far only works with square as a shape :)
def focsta(data, diameter, shape='square', start_angle=False, end_angle=False):
    
    data = np.array(data)
    
    if shape not in ('square', 'circular', 'retangular', 'wedge'):
        raise ValueError('Not a implemented shape.')
        
    
    if shape == 'square':
        return squarefun(data, diameter)
        
        
        
    elif shape == 'circular':
        pass
    
    
    elif shape == 'retangular':
        pass
        
        
    elif shape == 'wedge':
        pass


    
file = np.arange(60).reshape(10, 6) 

print(focsta(file, diameter=3)) # please test other files and diameters boys!! :)


[[ 7.  8.  9. 10. 11. 11.]
 [13. 14. 15. 16. 17. 17.]
 [19. 20. 21. 22. 23. 23.]
 [25. 26. 27. 28. 29. 29.]
 [31. 32. 33. 34. 35. 35.]
 [37. 38. 39. 40. 41. 41.]
 [43. 44. 45. 46. 47. 47.]
 [49. 50. 51. 52. 53. 53.]
 [55. 56. 57. 58. 59. 59.]
 [55. 56. 57. 58. 59. 59.]]


2. Based on the input in task 1, implement the circle, square and rectangular shape options. The wedge shape will grant you extra points.

3. Based on tasks 1 and 2 implement the image filter like explained at the beginning of this project description and in the Focal Statistics documentation. Implement the functions minimum, maximum and mean. If you implement standard deviation and variance, you will get extra points.