Image Processing Assignment


'''In this project, you will have to create an image-filtering tool that follows the same concept as the Focal Statistics from ArcGIS1. The idea is to create a moving window that calculates different statistics for every pixel neighborhood, given a specific size window. For example, let us take an image with gray values and a filtering window of 3 by 3 pixels to calculate a maximum filter (Figure 1). The center of the filtering window will be the object of focus every calculation step. Then, the pixel with higher value within the filtering window is assigned to the central pixel. This procedure runs through the whole image, resulting in a maximum filtered image. The same concept would be used for minimum, mean, standard deviation and variance descriptors.

You are allowed to create as many functions as you want. The design of the script is entirely up to you.
Good luck!
''''



<img src="images/Pic1.jpg" style="width: 650px"/>

Figure 1, the filtering window is a square (window length = window width). However, you can 
have circular windows (Figure 2a), rectangular windows (Figure 2b) or wedge windows (Figure 2c). 
The important issue to be aware of when window shapes are concerned, is that the central pixel 
must be in the right position, as highlighted in red in Figure 2.   

<img src="images/Pic2.jpg" style="width: 650px"/>

1. Implement a function that creates a filtering window based on the user input. These inputs must be basic parameters (i.e. radius, size and/or angles) of the filtering window, including shape type.

In [ ]:
import numpy as np


def bordercases(data, wsize_top, wsize_left, wsize_bot, wsize_right): 
    
    # filling newdata array with zeros
    newdata = np.zeros(data.shape)
    
    for col in range(np.size(data, 1)): # rows
            for row in range(np.size(data, 0)):  # columns



                ### border cases ###

                # all corners:
                if col < wsize_left and row < wsize_top: # topleft
                    window = data[:row+wsize_bot+1, :col+wsize_right+1]
                    #print('bot in topleft case \n', bot)

                elif col < wsize_left and row >= np.size(data, 0)-wsize_bot: # botleft
                    window = data[row-wsize_top:, :col+wsize_right+1]
                    #print('top in botleft case \n', top)


                elif col >= np.size(data, 1)-wsize_right and row < wsize_top: # topright
                    window = data[:row+wsize_bot+1, col-wsize_left:]
                    #print('bot in the topright case \n', bot)

                elif col >= np.size(data, 1)-wsize_right and row >= np.size(data, 0)-wsize_bot: # botright
                    window = data[row-wsize_top:, col-wsize_left:]
                    #print('top in the botright case \n', top)


                # all borders:
                elif col < wsize_left: # left border
                    window = data[row-wsize_top:row+wsize_bot+1, :col+(wsize_right)+1]
                    #print('left border case: \n', middle)

                elif row >= np.size(data, 0)-wsize_bot: # bot border
                    window = data[row-wsize_top:, col-wsize_left:col+wsize_right+1]
                    #print('bot border case \n', middle)

                elif col >= np.size(data, 1)-wsize_right: # right border
                    window = data[row-wsize_top:row+wsize_bot+1, col-wsize_left:]
                    #print('right border case \n', middle)

                elif row < wsize_top: # top border
                     window = data[:row+wsize_bot+1, col-wsize_left:col+wsize_right+1]
                    #print('top border case \n', middle)



                else: # normal case
                    window = data[row-wsize_top:row+wsize_bot+1, col-wsize_left:col+wsize_right+1]
                    #print('normal case \n', middle)


                # finding the maximum
                newdata[row, col] = np.max(window)
                #print(newdata)    
                
    return newdata


                
                
                
####################################### SHAPE FUNCTIONS ##############################################

# SQUARE #

def squarefun(data, diameter):
    data = np.array(data) 
    
    
              
    # diameter even -> central pixel is topleft
    if diameter%2==0:
        
        #small window size
        small_wsize = int((diameter-2)/2) # for top and left window
        big_wsize = int((diameter)/2) # for right and bot window
        
        newdata = bordercases(data, wsize_top = small_wsize, wsize_left = small_wsize, 
                              wsize_bot = big_wsize, wsize_right = big_wsize)
        
    
    else: # odd diameter
        

        # window size
        wsize = int((diameter-1)/2)
        
        newdata = bordercases(data, wsize, wsize, wsize, wsize) # for all sides the same window size


    return newdata
    
    
    
    
    
#################
#  Endfunction  #- so far only works with square as a shape :)
#################
def focsta(data, diameter, shape='square', start_angle=False, end_angle=False):
    
    data = np.array(data)
    
    if shape not in ('square', 'circular', 'retangular', 'wedge'):
        raise ValueError('Not a implemented shape.')
        
    
    if shape == 'square':
        return squarefun(data, diameter)
        
        
        
    elif shape == 'circular':
        pass
    
    
    elif shape == 'retangular':
        pass
        
        
    elif shape == 'wedge':
        pass


    
file = np.arange(60).reshape(10, 6) 
file2 = np.arange(start=60, stop=0, step=-1).reshape(10, 6) 

print('dia = 4 \n', focsta(file2, diameter=4))
print('dia = 5 \n', focsta(file2, diameter=5))

2. Based on the input in task 1, implement the circle, square and rectangular shape options. The wedge shape will grant you extra points.

In [ ]:
file = np.arange(60).reshape(10, 6) 
print(file)

3. Based on tasks 1 and 2 implement the image filter like explained at the beginning of this project description and in the Focal Statistics documentation. Implement the functions minimum, maximum and mean. If you implement standard deviation and variance, you will get extra points.

[[60 59 58 57 56 55]
 [54 53 52 51 50 49]
 [48 47 46 45 44 43]
 [42 41 40 39 38 37]
 [36 35 34 33 32 31]
 [30 29 28 27 26 25]
 [24 23 22 21 20 19]
 [18 17 16 15 14 13]
 [12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]
dia = 4 
 [[60. 60. 59. 58. 57. 56.]
 [60. 60. 59. 58. 57. 56.]
 [54. 54. 53. 52. 51. 50.]
 [48. 48. 47. 46. 45. 44.]
 [42. 42. 41. 40. 39. 38.]
 [36. 36. 35. 34. 33. 32.]
 [30. 30. 29. 28. 27. 26.]
 [24. 24. 23. 22. 21. 20.]
 [18. 18. 17. 16. 15. 14.]
 [12. 12. 11. 10.  9.  8.]]
dia = 5 
 [[60. 60. 60. 59. 58. 57.]
 [60. 60. 60. 59. 58. 57.]
 [60. 60. 60. 59. 58. 57.]
 [54. 54. 54. 53. 52. 51.]
 [48. 48. 48. 47. 46. 45.]
 [42. 42. 42. 41. 40. 39.]
 [36. 36. 36. 35. 34. 33.]
 [30. 30. 30. 29. 28. 27.]
 [24. 24. 24. 23. 22. 21.]
 [18. 18. 18. 17. 16. 15.]]
