Image Processing Assignment


'''In this project, you will have to create an image-filtering tool that follows the same concept as the Focal Statistics from ArcGIS1. The idea is to create a moving window that calculates different statistics for every pixel neighborhood, given a specific size window. For example, let us take an image with gray values and a filtering window of 3 by 3 pixels to calculate a maximum filter (Figure 1). The center of the filtering window will be the object of focus every calculation step. Then, the pixel with higher value within the filtering window is assigned to the central pixel. This procedure runs through the whole image, resulting in a maximum filtered image. The same concept would be used for minimum, mean, standard deviation and variance descriptors.

You are allowed to create as many functions as you want. The design of the script is entirely up to you.
Good
''''



1. Implement a function that creates a filtering window based on the user input. These inputs must be basic parameters (i.e. radius, size and/or angles) of the filtering window, including shape type.

In [8]:
# Hello Guilherme! This is a test!

import numpy as np

#creating 6x6 grid as an example
a = np.random.randint(36, size=(6, 6))
print('Array "a":\n {}'.format(a))






Array "a":
 [[31 10 16 21 13  9]
 [ 1 33  1  3 11 18]
 [18 26 25  8 16  8]
 [26 16 30 23 27  0]
 [21 25  5  4 29  2]
 [16  0  9 21 13  3]]


2. Based on the input in task 1, implement the circle, square and rectangular shape options. The wedge shape will grant you extra points.

In [4]:
import numpy as np

def focsta(shape = 'square', radius, start.angle = False, end.angle = False):
    
    if shape = 'square':
        pass
        
    elif shape = 'circular':
        pass
        
    elif shape = 'retangular':
        pass
    
    elif shape = 'wedge':
        pass
    
    else:
        return 'Not an implemented shape.'
        



SyntaxError: invalid syntax (<ipython-input-4-03958d8230af>, line 3)

3. Based on tasks 1 and 2 implement the image filter like explained at the beginning of this project description and in the Focal Statistics documentation. Implement the functions minimum, maximum and mean. If you implement standard deviation and variance, you will get extra points.

In [6]:

import numpy as np
??shape


Object `shape` not found.


ModuleNotFoundError: No module named 'geopandas'